/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LingshuPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var LingshuSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7075\u67A2\u8FDE\u63A5\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Token").setDesc("\u4ECE\u7075\u67A2\u7F51\u7AD9\u83B7\u53D6\u7684 API Token").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
        if (this.plugin.api) {
          this.plugin.api.updateToken(value);
        }
      });
      text.inputEl.type = "password";
      return text;
    });
    new import_obsidian.Setting(containerEl).setName("API \u5730\u5740").setDesc("\u7075\u67A2 API \u670D\u52A1\u5668\u5730\u5740").addText((text) => text.setPlaceholder("https://lingshu-api.cchang0727.workers.dev").setValue(this.plugin.settings.apiBaseUrl).onChange(async (value) => {
      this.plugin.settings.apiBaseUrl = value;
      await this.plugin.saveSettings();
      this.plugin.api.updateBaseUrl(value);
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u7F13\u5B58").setDesc("\u7F13\u5B58\u5206\u6790\u7ED3\u679C\u4EE5\u63D0\u9AD8\u6027\u80FD").addToggle((toggle) => toggle.setValue(this.plugin.settings.cacheEnabled).onChange(async (value) => {
      this.plugin.settings.cacheEnabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u5237\u65B0").setDesc("\u6587\u4EF6\u4FEE\u6539\u65F6\u81EA\u52A8\u5237\u65B0\u8FDE\u63A5").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRefresh).onChange(async (value) => {
      this.plugin.settings.autoRefresh = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4F7F\u7528\u6DF7\u5408\u6A21\u5F0F").setDesc("\u26A1 \u542F\u7528\u672C\u5730\u5FEB\u901F\u9884\u6D4B + \u4E91\u7AEF\u7CBE\u786E\u5206\u6790\uFF08\u63A8\u8350\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.useHybridMode).onChange(async (value) => {
      this.plugin.settings.useHybridMode = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u83B7\u53D6 API Token" });
    const instructions = containerEl.createDiv();
    instructions.innerHTML = `
            <ol>
                <li>\u8BBF\u95EE <a href="https://lingshu-app.pages.dev/index_zh.html">\u7075\u67A2\u7F51\u7AD9</a></li>
                <li>\u767B\u5F55\u4F60\u7684\u8D26\u53F7</li>
                <li>\u6253\u5F00\u6D4F\u89C8\u5668\u5F00\u53D1\u8005\u5DE5\u5177\uFF08F12\uFF09</li>
                <li>\u5728 Console \u4E2D\u8F93\u5165\uFF1A<code>localStorage.getItem('lingshu_auth_token')</code></li>
                <li>\u590D\u5236\u8FD4\u56DE\u7684 Token \u5E76\u7C98\u8D34\u5230\u4E0A\u65B9</li>
            </ol>
            <p><strong>\u26A0\uFE0F \u5B89\u5168\u63D0\u793A\uFF1A</strong></p>
            <ul>
                <li>\u8BF7\u52FF\u5C06 Token \u5206\u4EAB\u7ED9\u4ED6\u4EBA</li>
                <li>Token \u6709\u6548\u671F 30 \u5929\uFF0C\u8FC7\u671F\u540E\u9700\u91CD\u65B0\u83B7\u53D6</li>
            </ul>
        `;
    new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u6D4B\u8BD5 API \u8FDE\u63A5\u662F\u5426\u6B63\u5E38").addButton((button) => button.setButtonText("\u6D4B\u8BD5").onClick(async () => {
      if (!this.plugin.settings.apiToken) {
        button.setButtonText("\u274C \u8BF7\u5148\u914D\u7F6E Token");
        setTimeout(() => {
          button.setButtonText("\u6D4B\u8BD5");
        }, 2e3);
        return;
      }
      button.setButtonText("\u6D4B\u8BD5\u4E2D...");
      button.setDisabled(true);
      try {
        const result = await this.plugin.api.testConnection();
        if (result.success) {
          button.setButtonText("\u2705 \u8FDE\u63A5\u6210\u529F");
        } else {
          button.setButtonText(`\u274C ${result.error || "\u8FDE\u63A5\u5931\u8D25"}`);
        }
      } catch (error) {
        button.setButtonText("\u274C \u8FDE\u63A5\u5931\u8D25");
      }
      setTimeout(() => {
        button.setButtonText("\u6D4B\u8BD5");
        button.setDisabled(false);
      }, 2e3);
    }));
    new import_obsidian.Setting(containerEl).setName("\u6E05\u9664\u7F13\u5B58").setDesc("\u6E05\u9664\u6240\u6709\u672C\u5730\u7F13\u5B58\u6570\u636E").addButton((button) => button.setButtonText("\u6E05\u9664").setWarning().onClick(async () => {
      await this.plugin.cacheManager.clear();
      button.setButtonText("\u2705 \u5DF2\u6E05\u9664");
      setTimeout(() => {
        button.setButtonText("\u6E05\u9664");
      }, 2e3);
    }));
  }
};

// src/views/ConnectionsView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_LINGSHU = "lingshu-connections-view";
var LingshuConnectionsView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentConnections = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_LINGSHU;
  }
  getDisplayText() {
    return "\u7075\u67A2\u8FDE\u63A5";
  }
  getIcon() {
    return "brain-circuit";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("lingshu-connections-view");
    this.renderView();
  }
  async onClose() {
  }
  showError(message) {
    const container = this.containerEl.children[1];
    container.empty();
    const errorDiv = container.createDiv({ cls: "lingshu-error" });
    errorDiv.createEl("p", {
      text: "\u26A0\uFE0F " + message,
      cls: "lingshu-error-message"
    });
    errorDiv.createEl("p", {
      text: "\u8BF7\u68C0\u67E5\u7F51\u7EDC\u8FDE\u63A5\u6216\u7A0D\u540E\u91CD\u8BD5",
      cls: "lingshu-hint"
    });
  }
  showLoading(message = "\u6B63\u5728\u5206\u6790...") {
    const container = this.containerEl.children[1];
    container.empty();
    const loadingDiv = container.createDiv({ cls: "lingshu-loading" });
    loadingDiv.createEl("p", {
      text: "\u23F3 " + message,
      cls: "lingshu-loading-message"
    });
  }
  /**
   * 更新连接（带平滑过渡）
   */
  updateConnectionsSmooth(connections, isLocal = false) {
    if (isLocal && this.currentConnections.length > 0) {
      const hasCloudResults = this.currentConnections.some(
        (c) => c.connectionType !== "\u672C\u5730\u9884\u6D4B"
      );
      if (hasCloudResults) {
        return;
      }
    }
    this.updateConnections(connections);
  }
  renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    if (this.currentConnections.length === 0) {
      const empty = container.createDiv({ cls: "lingshu-empty" });
      empty.createEl("p", { text: "\u6682\u65E0\u8FDE\u63A5" });
      empty.createEl("p", {
        text: "\u6253\u5F00\u7B14\u8BB0\u540E\u81EA\u52A8\u5206\u6790",
        cls: "lingshu-hint"
      });
      return;
    }
    const stats = container.createDiv({ cls: "lingshu-stats" });
    const localCount = this.currentConnections.filter((c) => c.connectionType === "\u672C\u5730\u9884\u6D4B").length;
    const cloudCount = this.currentConnections.length - localCount;
    if (localCount > 0 && cloudCount === 0) {
      stats.createEl("span", {
        text: `\u{1F4CD} \u672C\u5730\u9884\u6D4B: ${localCount} \u4E2A\u8FDE\u63A5 (\u6B63\u5728\u83B7\u53D6\u7CBE\u786E\u7ED3\u679C...)`,
        cls: "lingshu-stats-text"
      });
    } else if (cloudCount > 0) {
      stats.createEl("span", {
        text: `\u2601\uFE0F AI \u5206\u6790: \u53D1\u73B0 ${cloudCount} \u4E2A\u8FDE\u63A5`,
        cls: "lingshu-stats-text"
      });
    } else {
      stats.createEl("span", {
        text: `\u53D1\u73B0 ${this.currentConnections.length} \u4E2A\u8FDE\u63A5`,
        cls: "lingshu-stats-text"
      });
    }
    const list = container.createDiv({ cls: "lingshu-connections-list" });
    this.currentConnections.forEach((conn) => {
      const isLocal = conn.connectionType === "\u672C\u5730\u9884\u6D4B";
      const itemClass = isLocal ? "lingshu-connection-item local-prediction" : "lingshu-connection-item cloud-result";
      const item = list.createDiv({ cls: itemClass });
      const arrow = item.createDiv({ cls: "lingshu-arrow" });
      arrow.setText("\u203A");
      const mainRow = item.createDiv({ cls: "lingshu-main-row" });
      const similarityBadge = mainRow.createDiv({ cls: "lingshu-similarity-badge" });
      similarityBadge.setText(`${(conn.similarity * 100).toFixed(0)}%`);
      const contentArea = mainRow.createDiv({ cls: "lingshu-content-area" });
      const titleLink = contentArea.createEl("a", {
        text: conn.targetTitle || "\u672A\u77E5\u6807\u9898",
        href: "#",
        cls: "internal-link lingshu-title"
      });
      titleLink.addEventListener("click", async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await this.openNote(conn.targetTitle);
      });
      if (conn.connectionType) {
        const isLocal2 = conn.connectionType === "\u672C\u5730\u9884\u6D4B";
        const tagClass = isLocal2 ? "lingshu-type-tag local" : "lingshu-type-tag cloud";
        contentArea.createSpan({
          cls: tagClass,
          text: conn.connectionType
        });
      }
      if (conn.explanation) {
        contentArea.createDiv({
          cls: "lingshu-explanation",
          text: conn.explanation
        });
      }
      const preview = item.createDiv({ cls: "lingshu-preview" });
      preview.style.display = "none";
      const loading = preview.createDiv({ cls: "lingshu-preview-loading" });
      loading.setText("\u52A0\u8F7D\u4E2D...");
      const togglePreview = async (e) => {
        const target = e.target;
        if (target.tagName === "A" || target.tagName === "BUTTON") {
          return;
        }
        const isExpanded = preview.style.display !== "none";
        if (isExpanded) {
          preview.style.display = "none";
          arrow.setText("\u203A");
          item.removeClass("expanded");
        } else {
          preview.style.display = "block";
          arrow.setText("\u25BE");
          item.addClass("expanded");
          if (loading.style.display !== "none") {
            await this.loadNotePreview(conn.targetTitle, preview, loading);
          }
        }
      };
      arrow.addEventListener("click", togglePreview);
      similarityBadge.addEventListener("click", togglePreview);
    });
  }
  async loadNotePreview(title, container, loading) {
    try {
      const files = this.app.vault.getMarkdownFiles();
      const file = files.find((f) => f.basename === title);
      if (!file) {
        loading.setText("\u627E\u4E0D\u5230\u7B14\u8BB0");
        return;
      }
      const content = await this.app.vault.read(file);
      loading.style.display = "none";
      const previewContent = container.createDiv({ cls: "lingshu-preview-content" });
      const lines = content.split("\n").slice(0, 30);
      lines.forEach((line) => {
        if (line.startsWith("# ")) {
          previewContent.createEl("h1", { text: line.substring(2) });
        } else if (line.startsWith("## ")) {
          previewContent.createEl("h2", { text: line.substring(3) });
        } else if (line.startsWith("### ")) {
          previewContent.createEl("h3", { text: line.substring(4) });
        } else if (line.startsWith("- ") || line.startsWith("* ")) {
          const li = previewContent.createEl("li", { text: line.substring(2) });
          li.style.marginLeft = "20px";
        } else if (line.trim()) {
          previewContent.createEl("p", { text: line });
        }
      });
    } catch (error) {
      loading.setText("\u52A0\u8F7D\u5931\u8D25");
      console.error("\u52A0\u8F7D\u7B14\u8BB0\u9884\u89C8\u5931\u8D25:", error);
    }
  }
  updateConnections(connections) {
    this.currentConnections = connections;
    this.renderView();
  }
  async openNote(title) {
    const files = this.app.vault.getMarkdownFiles();
    const file = files.find((f) => f.basename === title);
    if (file) {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
    } else {
      new import_obsidian2.Notice(`\u627E\u4E0D\u5230\u7B14\u8BB0: ${title}`);
    }
  }
};

// src/errors/ErrorHandler.ts
var import_obsidian3 = require("obsidian");
var LingshuError = class extends Error {
  constructor(type, message, userMessage, originalError) {
    super(message);
    this.type = type;
    this.userMessage = userMessage;
    this.actionable = this.isActionable(type);
    this.retryable = this.isRetryable(type);
    this.originalError = originalError;
  }
  isActionable(type) {
    return ["auth" /* AUTH_ERROR */, "network" /* NETWORK_ERROR */].includes(type);
  }
  isRetryable(type) {
    return ["network" /* NETWORK_ERROR */, "timeout" /* TIMEOUT_ERROR */, "api" /* API_ERROR */].includes(type);
  }
  static fromFetchError(error) {
    var _a, _b, _c;
    if (error.name === "TypeError" && error.message.includes("fetch")) {
      return new LingshuError(
        "network" /* NETWORK_ERROR */,
        "Network request failed",
        "\u65E0\u6CD5\u8FDE\u63A5\u5230\u7075\u67A2\u670D\u52A1\u5668\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u8FDE\u63A5",
        error
      );
    }
    if (((_a = error.message) == null ? void 0 : _a.includes("401")) || ((_b = error.message) == null ? void 0 : _b.includes("Unauthorized"))) {
      return new LingshuError(
        "auth" /* AUTH_ERROR */,
        "Authentication failed",
        "API Token \u5DF2\u8FC7\u671F\u6216\u65E0\u6548\uFF0C\u8BF7\u91CD\u65B0\u83B7\u53D6",
        error
      );
    }
    if ((_c = error.message) == null ? void 0 : _c.includes("timeout")) {
      return new LingshuError(
        "timeout" /* TIMEOUT_ERROR */,
        "Request timeout",
        "AI \u5206\u6790\u8D85\u65F6\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5",
        error
      );
    }
    return new LingshuError(
      "unknown" /* UNKNOWN_ERROR */,
      error.message || "Unknown error",
      "\u53D1\u751F\u672A\u77E5\u9519\u8BEF\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5",
      error
    );
  }
};
var ErrorHandler = class {
  constructor(app) {
    this.app = app;
  }
  async handle(error, context) {
    console.error(`[Lingshu Error] ${context || ""}:`, error);
    switch (error.type) {
      case "network" /* NETWORK_ERROR */:
        return await this.handleNetworkError(error);
      case "auth" /* AUTH_ERROR */:
        return await this.handleAuthError(error);
      case "timeout" /* TIMEOUT_ERROR */:
        return await this.handleTimeoutError(error);
      case "api" /* API_ERROR */:
        return await this.handleAPIError(error);
      default:
        return await this.handleUnknownError(error);
    }
  }
  async handleNetworkError(error) {
    const modal = new ErrorModal(
      this.app,
      "\u7F51\u7EDC\u8FDE\u63A5\u5931\u8D25",
      error.userMessage,
      [
        { label: "\u91CD\u8BD5", action: "retry" /* RETRY */ },
        { label: "\u4F7F\u7528\u7F13\u5B58", action: "use_cache" /* USE_CACHE */ },
        { label: "\u53D6\u6D88", action: "cancel" /* CANCEL */ }
      ]
    );
    return await modal.show();
  }
  async handleAuthError(error) {
    const modal = new ErrorModal(
      this.app,
      "Token \u5DF2\u8FC7\u671F",
      error.userMessage + "\n\n\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u91CD\u65B0\u914D\u7F6E API Token",
      [
        { label: "\u6253\u5F00\u8BBE\u7F6E", action: "open_settings" /* OPEN_SETTINGS */ },
        { label: "\u53D6\u6D88", action: "cancel" /* CANCEL */ }
      ]
    );
    return await modal.show();
  }
  async handleTimeoutError(error) {
    new import_obsidian3.Notice("\u23F1\uFE0F AI \u5206\u6790\u8D85\u65F6\uFF0C\u5DF2\u52A0\u5165\u961F\u5217\uFF0C\u7A0D\u540E\u4F1A\u81EA\u52A8\u5B8C\u6210");
    return "queue" /* QUEUE */;
  }
  async handleAPIError(error) {
    new import_obsidian3.Notice(`\u274C ${error.userMessage}`);
    return "cancel" /* CANCEL */;
  }
  async handleUnknownError(error) {
    const modal = new ErrorModal(
      this.app,
      "\u672A\u77E5\u9519\u8BEF",
      error.userMessage,
      [
        { label: "\u53D6\u6D88", action: "cancel" /* CANCEL */ }
      ]
    );
    return await modal.show();
  }
};
var ErrorModal = class extends import_obsidian3.Modal {
  constructor(app, title, message, actions) {
    super(app);
    this.title = title;
    this.message = message;
    this.actions = actions;
  }
  show() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      this.open();
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    this.actions.forEach(({ label, action }) => {
      const button = buttonContainer.createEl("button", { text: label });
      button.addEventListener("click", () => {
        this.close();
        this.resolve(action);
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/utils/retry.ts
async function retryWithBackoff(fn, options = {}) {
  const {
    maxRetries = 3,
    baseDelay = 1e3,
    maxDelay = 1e4,
    onRetry
  } = options;
  let lastError;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      if (attempt === maxRetries) {
        throw lastError;
      }
      const delay = Math.min(baseDelay * Math.pow(2, attempt), maxDelay);
      console.log(`[Retry] \u5C1D\u8BD5 ${attempt + 1}/${maxRetries} \u5931\u8D25\uFF0C${delay}ms \u540E\u91CD\u8BD5`);
      if (onRetry) {
        onRetry(attempt + 1, maxRetries, delay);
      }
      await sleep(delay);
    }
  }
  throw lastError;
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// src/api/OptimizedLingshuAPI.ts
var OptimizedLingshuAPI = class {
  // 上传队列
  constructor(baseUrl, token, cacheManager) {
    this.uploadingArticles = /* @__PURE__ */ new Set();
    // 正在上传的文章标题
    this.uploadQueue = Promise.resolve();
    this.baseUrl = baseUrl;
    this.token = token;
    this.cacheManager = cacheManager;
  }
  async analyzeNoteWithCache(title, content) {
    const contentHash = this.cacheManager.calculateHash(content);
    const cachedAnyVersion = await this.cacheManager.getByTitle(title);
    const cached = await this.cacheManager.get(title, contentHash);
    if (cached && !cached.uploading) {
      console.log("[API] \u2705 \u4F7F\u7528\u672C\u5730\u7F13\u5B58");
      const filteredConnections = cached.connections.filter(
        (conn) => conn.targetTitle !== title
      );
      return {
        connections: filteredConnections,
        fromCache: true
      };
    }
    if (cachedAnyVersion && cachedAnyVersion.articleId && cachedAnyVersion.articleId !== "" && !cachedAnyVersion.uploading) {
      try {
        const connections = await this.getConnections(cachedAnyVersion.articleId);
        const filteredConnections = connections.filter(
          (conn) => conn.targetTitle !== title
        );
        await this.cacheManager.set({
          title,
          contentHash,
          connections: filteredConnections,
          articleId: cachedAnyVersion.articleId,
          timestamp: Date.now(),
          uploading: false
        });
        return {
          connections: filteredConnections,
          fromCache: false
        };
      } catch (error) {
        console.warn("[API] \u83B7\u53D6\u8FDE\u63A5\u5931\u8D25\uFF0C\u5C06\u91CD\u65B0\u4E0A\u4F20");
      }
    }
    if (cached && cached.uploading || cachedAnyVersion && cachedAnyVersion.uploading) {
      console.log("[API] \u23F3 \u6587\u7AE0\u6B63\u5728\u4E0A\u4F20\u4E2D\uFF0C\u7B49\u5F85...");
      await new Promise((resolve) => window.setTimeout(resolve, 2e3));
      return this.analyzeNoteWithCache(title, content);
    }
    try {
      const cloudArticle = await this.findArticleByTitle(title);
      if (cloudArticle) {
        console.log("[API] \u2601\uFE0F \u627E\u5230\u4E91\u7AEF\u6587\u7AE0\uFF0C\u83B7\u53D6\u8FDE\u63A5");
        const connections = await this.getConnections(cloudArticle.id);
        const filteredConnections = connections.filter(
          (conn) => conn.targetTitle !== title
        );
        await this.cacheManager.set({
          title,
          contentHash,
          connections: filteredConnections,
          articleId: cloudArticle.id,
          timestamp: Date.now(),
          uploading: false
        });
        return {
          connections: filteredConnections,
          fromCache: false
        };
      }
      if (this.uploadingArticles.has(title)) {
        console.log("[API] \u23F3 \u6587\u7AE0\u6B63\u5728\u4E0A\u4F20\u4E2D\uFF08\u5185\u5B58\u9501\uFF09\uFF0C\u7B49\u5F85...");
        await new Promise((resolve) => window.setTimeout(resolve, 2e3));
        return this.analyzeNoteWithCache(title, content);
      }
      return await this.enqueueUpload(title, content, contentHash);
    } catch (error) {
      console.error("[API] \u274C \u8BF7\u6C42\u5931\u8D25:", error);
      throw LingshuError.fromFetchError(error);
    }
  }
  async enqueueUpload(title, content, contentHash) {
    const uploadTask = async () => {
      this.uploadingArticles.add(title);
      await this.cacheManager.set({
        title,
        contentHash,
        connections: [],
        articleId: "",
        timestamp: Date.now(),
        uploading: true
      });
      try {
        const result = await this.createAndAnalyze(title, content, contentHash);
        return result;
      } catch (error) {
        await this.cacheManager.clear(title);
        throw error;
      } finally {
        this.uploadingArticles.delete(title);
      }
    };
    const previousQueue = this.uploadQueue;
    const currentTask = previousQueue.then(uploadTask, uploadTask);
    this.uploadQueue = currentTask.catch(() => {
    });
    return await currentTask;
  }
  async createAndAnalyze(title, content, contentHash) {
    const result = await retryWithBackoff(
      () => this.createArticle(title, content),
      {
        maxRetries: 3,
        onRetry: (attempt, max) => {
          console.log(`[API] \u91CD\u8BD5\u4E2D... (${attempt}/${max})`);
        }
      }
    );
    if (!result.articleId) {
      throw new LingshuError(
        "api" /* API_ERROR */,
        "No article ID returned",
        "\u521B\u5EFA\u6587\u7AE0\u5931\u8D25"
      );
    }
    const connections = await this.waitForAnalysis(result.articleId);
    const filteredConnections = connections.filter(
      (conn) => conn.targetTitle !== title
    );
    await this.cacheManager.set({
      title,
      contentHash,
      connections: filteredConnections,
      articleId: result.articleId,
      timestamp: Date.now(),
      uploading: false
    });
    return {
      connections: filteredConnections,
      fromCache: false
    };
  }
  async findArticleByTitle(title) {
    try {
      const response = await fetch(
        `${this.baseUrl}/api/articles?search=${encodeURIComponent(title)}&limit=50`,
        {
          headers: {
            "Authorization": `Bearer ${this.token}`
          }
        }
      );
      if (!response.ok) {
        console.log("[API] \u67E5\u627E\u6587\u7AE0\u5931\u8D25\uFF0C\u72B6\u6001\u7801:", response.status);
        return null;
      }
      const data = await response.json();
      const articles = data.articles || [];
      const exactMatch = articles.find((a) => a.title === title);
      if (exactMatch) {
        console.log("[API] \u2705 \u627E\u5230\u7CBE\u786E\u5339\u914D\u7684\u6587\u7AE0:", title);
      } else {
        console.log("[API] \u2139\uFE0F \u672A\u627E\u5230\u6587\u7AE0:", title);
      }
      return exactMatch || null;
    } catch (error) {
      console.error("[API] \u67E5\u627E\u6587\u7AE0\u5F02\u5E38:", error);
      return null;
    }
  }
  async createArticle(title, content) {
    var _a;
    const response = await fetch(`${this.baseUrl}/api/articles`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.token}`
      },
      body: JSON.stringify({
        title,
        content,
        author: "Obsidian User",
        url: `obsidian://note/${encodeURIComponent(title)}`
      })
    });
    if (!response.ok) {
      const errorText = await response.text();
      let errorMessage = "\u521B\u5EFA\u6587\u7AE0\u5931\u8D25";
      try {
        const errorJson = JSON.parse(errorText);
        errorMessage = ((_a = errorJson.error) == null ? void 0 : _a.message) || errorMessage;
      } catch (e) {
      }
      throw new Error(errorMessage);
    }
    return await response.json();
  }
  async getConnections(articleId) {
    const response = await fetch(
      `${this.baseUrl}/api/articles/${articleId}/connections`,
      {
        headers: {
          "Authorization": `Bearer ${this.token}`
        }
      }
    );
    if (!response.ok) {
      throw new Error("\u83B7\u53D6\u8FDE\u63A5\u5931\u8D25");
    }
    const data = await response.json();
    const connections = data.connections || [];
    const mapped = connections.map((conn) => ({
      targetId: conn.target_id,
      targetTitle: conn.target_title,
      similarity: conn.similarity,
      connectionType: conn.connection_type,
      explanation: conn.explanation
    }));
    return mapped;
  }
  async waitForAnalysis(articleId, maxAttempts = 30) {
    console.log("[API] \u23F3 \u7B49\u5F85 AI \u5206\u6790...");
    for (let i = 0; i < maxAttempts; i++) {
      await new Promise((resolve) => setTimeout(resolve, 2e3));
      try {
        const connections = await this.getConnections(articleId);
        if (connections.length > 0) {
          console.log(`[API] \u2705 \u5206\u6790\u5B8C\u6210\uFF0C\u53D1\u73B0 ${connections.length} \u4E2A\u8FDE\u63A5`);
          return connections;
        }
      } catch (error) {
      }
      if (i > 0 && i % 5 === 0) {
        console.log(`[API] \u23F3 \u5206\u6790\u4E2D... (${i * 2}s)`);
      }
    }
    console.log("[API] \u23F1\uFE0F AI \u5206\u6790\u8D85\u65F6\uFF0C\u672A\u53D1\u73B0\u8FDE\u63A5");
    return [];
  }
  async testConnection() {
    try {
      const response = await fetch(`${this.baseUrl}/health`);
      const data = await response.json();
      return { success: data.success };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"
      };
    }
  }
  updateToken(token) {
    this.token = token;
  }
  updateBaseUrl(baseUrl) {
    this.baseUrl = baseUrl;
  }
};

// src/utils/localSimilarity.ts
var LocalSimilarityCalculator = class {
  /**
   * 中文分词（简单版 - 提取 2-4 字词组）
   */
  tokenizeChinese(text) {
    const cleaned = text.replace(/[，。！？；：""''（）【】《》、\s]/g, " ");
    const chineseChars = cleaned.match(/[\u4e00-\u9fa5]+/g) || [];
    const ngrams = [];
    chineseChars.forEach((segment) => {
      if (segment.length < 2)
        return;
      for (let i = 0; i < segment.length - 1; i++) {
        ngrams.push(segment.substring(i, i + 2));
      }
      for (let i = 0; i < segment.length - 2; i++) {
        ngrams.push(segment.substring(i, i + 3));
      }
      if (segment.length >= 4) {
        for (let i = 0; i < segment.length - 3; i++) {
          ngrams.push(segment.substring(i, i + 4));
        }
      }
    });
    return ngrams;
  }
  /**
   * 英文分词
   */
  tokenizeEnglish(text) {
    return text.toLowerCase().replace(/[^\w\s]/g, " ").split(/\s+/).filter((w) => w.length > 2);
  }
  /**
   * 通用分词（中英文混合）
   */
  tokenize(text) {
    const chineseTokens = this.tokenizeChinese(text);
    const englishTokens = this.tokenizeEnglish(text);
    return [...chineseTokens, ...englishTokens];
  }
  /**
   * 计算 Jaccard 相似度（快速但粗糙）
   */
  calculateJaccard(text1, text2) {
    const words1 = new Set(this.tokenize(text1));
    const words2 = new Set(this.tokenize(text2));
    if (words1.size === 0 || words2.size === 0)
      return 0;
    const intersection = new Set(
      [...words1].filter((w) => words2.has(w))
    );
    const union = /* @__PURE__ */ new Set([...words1, ...words2]);
    return intersection.size / union.size;
  }
  /**
   * 快速预筛选候选文档
   */
  quickFilter(query, candidates, threshold = 0.05, limit = 20) {
    return candidates.map((c) => ({
      title: c.title,
      score: this.calculateJaccard(query, c.title + " " + c.content)
    })).filter((c) => c.score > threshold).sort((a, b) => b.score - a.score).slice(0, limit);
  }
  /**
   * 提取关键词（TF-IDF）
   */
  extractKeywords(text, topN = 10) {
    const words = this.tokenize(text);
    const freq = /* @__PURE__ */ new Map();
    words.forEach((w) => {
      freq.set(w, (freq.get(w) || 0) + 1);
    });
    const stopWords = /* @__PURE__ */ new Set([
      "the",
      "is",
      "at",
      "which",
      "on",
      "and",
      "or",
      "but",
      "\u7684",
      "\u4E86",
      "\u5728",
      "\u662F",
      "\u6211",
      "\u6709",
      "\u548C",
      "\u5C31",
      "\u4E0D",
      "\u4EBA",
      "\u90FD",
      "\u4E00",
      "\u4E00\u4E2A",
      "\u4E0A",
      "\u4E5F",
      "\u5F88",
      "\u5230",
      "\u8BF4",
      "\u8981",
      "\u53BB"
    ]);
    return Array.from(freq.entries()).filter(([word]) => !stopWords.has(word)).sort((a, b) => b[1] - a[1]).slice(0, topN).map(([word]) => word);
  }
  /**
   * 计算余弦相似度（更精确但稍慢）
   */
  calculateCosine(text1, text2) {
    const words1 = this.tokenize(text1);
    const words2 = this.tokenize(text2);
    const allWords = /* @__PURE__ */ new Set([...words1, ...words2]);
    const freq1 = /* @__PURE__ */ new Map();
    const freq2 = /* @__PURE__ */ new Map();
    words1.forEach((w) => freq1.set(w, (freq1.get(w) || 0) + 1));
    words2.forEach((w) => freq2.set(w, (freq2.get(w) || 0) + 1));
    let dotProduct = 0;
    let magnitude1 = 0;
    let magnitude2 = 0;
    allWords.forEach((word) => {
      const f1 = freq1.get(word) || 0;
      const f2 = freq2.get(word) || 0;
      dotProduct += f1 * f2;
      magnitude1 += f1 * f1;
      magnitude2 += f2 * f2;
    });
    if (magnitude1 === 0 || magnitude2 === 0)
      return 0;
    return dotProduct / (Math.sqrt(magnitude1) * Math.sqrt(magnitude2));
  }
};

// src/api/HybridAnalyzer.ts
var HybridAnalyzer = class {
  constructor(app, cloudAPI, cacheManager) {
    this.app = app;
    this.cloudAPI = cloudAPI;
    this.cacheManager = cacheManager;
    this.localCalculator = new LocalSimilarityCalculator();
  }
  /**
   * 混合分析：先本地快速，再云端精确
   */
  async analyze(title, content, onLocalResult, onCloudResult) {
    const localConnections = await this.localAnalyze(title, content);
    if (onLocalResult && localConnections.length > 0) {
      onLocalResult(localConnections);
    }
    const cloudConnections = await this.cloudAPI.analyzeNoteWithCache(title, content);
    if (onCloudResult) {
      onCloudResult(cloudConnections.connections);
    }
    return {
      local: localConnections,
      cloud: cloudConnections.connections
    };
  }
  /**
   * 本地快速分析（优化版：优先使用缓存）
   */
  async localAnalyze(title, content) {
    const startTime = Date.now();
    const cachedEntries = this.cacheManager.getAllCached();
    const candidates = [];
    if (cachedEntries.length > 0) {
      for (const cached of cachedEntries) {
        if (cached.title === title)
          continue;
        try {
          const file = this.app.vault.getMarkdownFiles().find((f) => f.basename === cached.title);
          if (file) {
            const fileContent = await this.app.vault.read(file);
            candidates.push({
              title: cached.title,
              content: fileContent
            });
          }
        } catch (error) {
        }
      }
    }
    if (candidates.length < 20) {
      const allFiles = this.app.vault.getMarkdownFiles();
      const recentFiles = allFiles.sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, 50);
      for (const file of recentFiles) {
        if (file.basename === title)
          continue;
        if (candidates.some((c) => c.title === file.basename))
          continue;
        try {
          const fileContent = await this.app.vault.read(file);
          candidates.push({
            title: file.basename,
            content: fileContent
          });
          if (candidates.length >= 50)
            break;
        } catch (error) {
        }
      }
    }
    if (candidates.length === 0) {
      console.log("[HybridAnalyzer] \u6CA1\u6709\u53EF\u7528\u7684\u5019\u9009\u7B14\u8BB0");
      return [];
    }
    const results = this.localCalculator.quickFilter(
      content,
      candidates,
      0.05,
      // 阈值
      10
      // 最多 10 个
    );
    const elapsed = Date.now() - startTime;
    console.log(`[HybridAnalyzer] \u672C\u5730\u5206\u6790\u5B8C\u6210: ${results.length} \u4E2A\u7ED3\u679C, \u8017\u65F6 ${elapsed}ms`);
    return results.map((r) => ({
      targetId: "",
      targetTitle: r.title,
      similarity: r.score,
      connectionType: "\u672C\u5730\u9884\u6D4B",
      explanation: "\u57FA\u4E8E\u5173\u952E\u8BCD\u76F8\u4F3C\u5EA6\u7684\u5FEB\u901F\u9884\u6D4B"
    }));
  }
};

// src/cache/CacheManager.ts
var CacheManager = class {
  constructor(app) {
    this.CACHE_EXPIRY = 24 * 60 * 60 * 1e3;
    // 24 小时
    this.CACHE_VERSION = 2;
    this.app = app;
    this.cache = /* @__PURE__ */ new Map();
  }
  setSaveCallback(callback) {
    this.saveCallback = callback;
  }
  calculateHash(content) {
    let hash = 0;
    for (let i = 0; i < content.length; i++) {
      const char = content.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(36);
  }
  /**
   * 根据标题获取缓存（不检查内容哈希）
   */
  async getByTitle(title) {
    const cached = this.cache.get(title);
    if (!cached) {
      return null;
    }
    const now = Date.now();
    if (now - cached.timestamp > this.CACHE_EXPIRY) {
      console.log("[Cache] \u7F13\u5B58\u5DF2\u8FC7\u671F");
      this.cache.delete(title);
      await this.persist();
      return null;
    }
    return cached;
  }
  async get(title, contentHash) {
    const cached = this.cache.get(title);
    if (!cached) {
      return null;
    }
    if (!cached.version || cached.version < this.CACHE_VERSION) {
      console.log("[Cache] \u7F13\u5B58\u7248\u672C\u8FC7\u65E7\uFF0C\u81EA\u52A8\u6E05\u9664");
      this.cache.delete(title);
      return null;
    }
    if (cached.connections && cached.connections.length > 0) {
      const hasInvalidConnection = cached.connections.some(
        (conn) => !conn.targetTitle || conn.targetTitle === "\u672A\u77E5\u6807\u9898"
      );
      if (hasInvalidConnection) {
        console.log("[Cache] \u7F13\u5B58\u6570\u636E\u4E0D\u5B8C\u6574\uFF0C\u81EA\u52A8\u6E05\u9664");
        this.cache.delete(title);
        return null;
      }
    }
    if (cached.contentHash !== contentHash) {
      console.log("[Cache] \u5185\u5BB9\u5DF2\u53D8\u5316\uFF0C\u7F13\u5B58\u5931\u6548");
      this.cache.delete(title);
      return null;
    }
    const age = Date.now() - cached.timestamp;
    if (age > this.CACHE_EXPIRY) {
      console.log("[Cache] \u7F13\u5B58\u5DF2\u8FC7\u671F");
      this.cache.delete(title);
      return null;
    }
    console.log("[Cache] \u547D\u4E2D\u7F13\u5B58");
    return cached;
  }
  async set(entry) {
    this.cache.set(entry.title, {
      ...entry,
      version: this.CACHE_VERSION,
      timestamp: Date.now()
    });
    await this.persist();
  }
  async clear(title) {
    if (title) {
      this.cache.delete(title);
    } else {
      this.cache.clear();
    }
    await this.persist();
  }
  /**
   * 清理所有 uploading 标记（用于启动时清理）
   */
  async clearUploadingFlags() {
    let cleaned = 0;
    for (const [title, entry] of this.cache.entries()) {
      if (entry.uploading) {
        entry.uploading = false;
        cleaned++;
      }
    }
    if (cleaned > 0) {
      console.log(`[Cache] \u6E05\u7406\u4E86 ${cleaned} \u4E2A\u4E0A\u4F20\u6807\u8BB0`);
      await this.persist();
    }
  }
  async persist() {
    if (this.saveCallback) {
      await this.saveCallback();
    }
  }
  async load(data) {
    if (data && data.cache) {
      this.cache = new Map(Object.entries(data.cache));
    }
  }
  toJSON() {
    return {
      cache: Object.fromEntries(this.cache.entries())
    };
  }
  getStats() {
    const now = Date.now();
    let expired = 0;
    for (const entry of this.cache.values()) {
      if (now - entry.timestamp > this.CACHE_EXPIRY) {
        expired++;
      }
    }
    const jsonStr = JSON.stringify(Array.from(this.cache.entries()));
    const bytes = new TextEncoder().encode(jsonStr).length;
    return {
      total: this.cache.size,
      expired,
      size: this.formatSize(bytes)
    };
  }
  formatSize(bytes) {
    if (bytes < 1024)
      return bytes + " B";
    if (bytes < 1024 * 1024)
      return (bytes / 1024).toFixed(2) + " KB";
    return (bytes / (1024 * 1024)).toFixed(2) + " MB";
  }
  /**
   * 获取所有缓存的笔记（用于本地预测）
   */
  getAllCached() {
    const now = Date.now();
    const validEntries = [];
    for (const entry of this.cache.values()) {
      if (now - entry.timestamp <= this.CACHE_EXPIRY && !entry.uploading) {
        validEntries.push(entry);
      }
    }
    return validEntries;
  }
  /**
   * 检查是否有缓存
   */
  has(title) {
    return this.cache.has(title);
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  apiToken: "",
  apiBaseUrl: "https://lingshu-api.cchang0727.workers.dev",
  autoRefresh: true,
  cacheEnabled: true,
  useHybridMode: false
  // 暂时关闭混合模式，先解决重复问题
};
var LingshuPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.autoAnalysisTimeout = null;
    this.currentAnalysisTitle = null;
    this.analyzingNotes = /* @__PURE__ */ new Set();
  }
  async onload() {
    console.log("Loading Lingshu Plugin v1.0.0");
    await this.loadSettings();
    this.cacheManager = new CacheManager(this.app);
    this.cacheManager.setSaveCallback(async () => {
      const data2 = await this.loadData() || {};
      Object.assign(data2, this.cacheManager.toJSON());
      await this.saveData(data2);
    });
    const data = await this.loadData();
    if (data) {
      await this.cacheManager.load(data);
      await this.cacheManager.clearUploadingFlags();
    }
    this.errorHandler = new ErrorHandler(this.app);
    this.api = new OptimizedLingshuAPI(
      this.settings.apiBaseUrl,
      this.settings.apiToken,
      this.cacheManager
    );
    this.hybridAnalyzer = new HybridAnalyzer(this.app, this.api, this.cacheManager);
    this.registerView(
      VIEW_TYPE_LINGSHU,
      (leaf) => new LingshuConnectionsView(leaf, this)
    );
    this.addRibbonIcon("brain-circuit", "\u7075\u67A2\u8FDE\u63A5", () => {
      this.activateView();
    });
    this.addCommand({
      id: "analyze-current-note",
      name: "\u5206\u6790\u5F53\u524D\u7B14\u8BB0",
      callback: () => {
        this.analyzeCurrentNote();
      }
    });
    this.addCommand({
      id: "clear-cache",
      name: "\u6E05\u9664\u7F13\u5B58",
      callback: async () => {
        await this.cacheManager.clear();
        new import_obsidian4.Notice("\u2705 \u7F13\u5B58\u5DF2\u6E05\u9664");
      }
    });
    this.addCommand({
      id: "show-cache-stats",
      name: "\u67E5\u770B\u7F13\u5B58\u7EDF\u8BA1",
      callback: () => {
        const stats = this.cacheManager.getStats();
        new import_obsidian4.Notice(
          `\u7F13\u5B58\u7EDF\u8BA1:
\u603B\u6570: ${stats.total}
\u8FC7\u671F: ${stats.expired}
\u5927\u5C0F: ${stats.size}`
        );
      }
    });
    this.addSettingTab(new LingshuSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file && this.settings.autoRefresh) {
          this.scheduleAutoAnalysis();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.getViewType()) === VIEW_TYPE_LINGSHU) {
          const activeFile = this.app.workspace.getActiveFile();
          if (activeFile && this.settings.autoRefresh) {
            const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
            if (leaves.length > 0) {
              const view = leaves[0].view;
              if (view.containerEl.children[1].childElementCount === 0) {
                this.scheduleAutoAnalysis();
              }
            }
          }
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });
  }
  // 当前正在分析的笔记
  /**
   * 延迟自动分析（防抖）
   */
  scheduleAutoAnalysis() {
    if (this.autoAnalysisTimeout) {
      window.clearTimeout(this.autoAnalysisTimeout);
    }
    this.autoAnalysisTimeout = window.setTimeout(() => {
      this.autoAnalyzeCurrentNote();
    }, 2e3);
  }
  // 正在分析的笔记
  /**
   * 自动分析当前笔记（静默模式，不显示通知）
   */
  async autoAnalyzeCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || !this.settings.apiToken) {
      return;
    }
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
    if (leaves.length === 0) {
      return;
    }
    const view = leaves[0].view;
    const container = view.containerEl;
    if (typeof container.checkVisibility === "function" && container.checkVisibility() === false) {
      return;
    }
    const title = activeFile.basename;
    if (this.analyzingNotes.has(title)) {
      console.log("[Plugin] \u23ED\uFE0F \u8DF3\u8FC7\u91CD\u590D\u5206\u6790:", title);
      return;
    }
    if (this.currentAnalysisTitle && this.currentAnalysisTitle !== title) {
      console.log("[Plugin] \u{1F6AB} \u53D6\u6D88\u65E7\u5206\u6790:", this.currentAnalysisTitle);
      this.analyzingNotes.delete(this.currentAnalysisTitle);
    }
    this.currentAnalysisTitle = title;
    this.analyzingNotes.add(title);
    try {
      const content = await this.app.vault.read(activeFile);
      if (this.currentAnalysisTitle !== title) {
        console.log("[Plugin] \u{1F6AB} \u7B14\u8BB0\u5DF2\u5207\u6362\uFF0C\u653E\u5F03\u5206\u6790:", title);
        return;
      }
      const leaves2 = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
      if (leaves2.length === 0)
        return;
      const view2 = leaves2[0].view;
      if (this.settings.useHybridMode) {
        view2.showLoading("\u6B63\u5728\u5206\u6790...");
        await this.hybridAnalyzer.analyze(
          title,
          content,
          // 本地结果回调
          (localConnections) => {
            if (this.currentAnalysisTitle === title && localConnections.length > 0) {
              console.log("[Plugin] \u{1F4CD} \u663E\u793A\u672C\u5730\u9884\u6D4B\u7ED3\u679C");
              view2.updateConnectionsSmooth(localConnections, true);
            }
          },
          // 云端结果回调
          (cloudConnections) => {
            if (this.currentAnalysisTitle === title) {
              console.log("[Plugin] \u2601\uFE0F \u66F4\u65B0\u4E3A\u4E91\u7AEF\u7ED3\u679C");
              view2.updateConnectionsSmooth(cloudConnections, false);
            }
          }
        );
      } else {
        const result = await this.api.analyzeNoteWithCache(title, content);
        if (this.currentAnalysisTitle === title) {
          view2.updateConnections(result.connections);
        }
      }
    } catch (error) {
      console.warn("\u81EA\u52A8\u5206\u6790\u5931\u8D25:", error);
      const leaves2 = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
      if (leaves2.length > 0) {
        const view2 = leaves2[0].view;
        view2.showError("\u5206\u6790\u5931\u8D25");
      }
    } finally {
      this.analyzingNotes.delete(title);
      if (this.currentAnalysisTitle === title) {
        this.currentAnalysisTitle = null;
      }
    }
  }
  async onunload() {
    console.log("Unloading Lingshu Plugin");
    if (this.autoAnalysisTimeout) {
      window.clearTimeout(this.autoAnalysisTimeout);
    }
    await this.cacheManager.persist();
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data && data.settings) {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data.settings);
    } else {
      this.settings = Object.assign({}, DEFAULT_SETTINGS);
    }
  }
  async saveSettings() {
    const data = await this.loadData() || {};
    data.settings = this.settings;
    await this.saveData(data);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_LINGSHU)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_LINGSHU, active: true });
      } else {
        leaf = workspace.getLeaf(false);
        await leaf.setViewState({ type: VIEW_TYPE_LINGSHU, active: true });
      }
    }
    workspace.revealLeaf(leaf);
  }
  async analyzeCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian4.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
      return;
    }
    if (!this.settings.apiToken) {
      new import_obsidian4.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Token");
      return;
    }
    try {
      const content = await this.app.vault.read(activeFile);
      const title = activeFile.basename;
      new import_obsidian4.Notice("\u{1F50D} \u6B63\u5728\u5206\u6790\u7B14\u8BB0...");
      const result = await this.api.analyzeNoteWithCache(title, content);
      if (result.fromCache) {
        new import_obsidian4.Notice(`\u2705 \u53D1\u73B0 ${result.connections.length} \u4E2A\u8FDE\u63A5\uFF08\u6765\u81EA\u7F13\u5B58\uFF09`);
      } else {
        new import_obsidian4.Notice(`\u2705 \u5206\u6790\u5B8C\u6210\uFF01\u53D1\u73B0 ${result.connections.length} \u4E2A\u8FDE\u63A5`);
      }
      const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
      if (leaves.length > 0) {
        const view = leaves[0].view;
        view.updateConnections(result.connections);
      }
      await this.activateView();
    } catch (error) {
      console.error("\u5206\u6790\u5931\u8D25:", error);
      const lingshuError = error instanceof LingshuError ? error : LingshuError.fromFetchError(error);
      const action = await this.errorHandler.handle(lingshuError, "\u5206\u6790\u7B14\u8BB0");
      switch (action) {
        case "retry" /* RETRY */:
          await this.analyzeCurrentNote();
          break;
        case "use_cache" /* USE_CACHE */:
          const cached = await this.cacheManager.get(
            activeFile.basename,
            this.cacheManager.calculateHash(await this.app.vault.read(activeFile))
          );
          if (cached) {
            new import_obsidian4.Notice(`\u2705 \u4F7F\u7528\u7F13\u5B58\uFF1A${cached.connections.length} \u4E2A\u8FDE\u63A5`);
            const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_LINGSHU);
            if (leaves.length > 0) {
              const view = leaves[0].view;
              view.updateConnections(cached.connections);
            }
            await this.activateView();
          }
          break;
        case "open_settings" /* OPEN_SETTINGS */:
          this.app.setting.open();
          this.app.setting.openTabById("lingshu-connections");
          break;
      }
    }
  }
};
